"""add key rates

Revision ID: 9ed4c9dd4b75
Revises: 47f527d22897
Create Date: 2026-06-11 04:43:41.973167

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9ed4c9dd4b75"
down_revision: str | Sequence[str] | None = "47f527d22897"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "key_rates",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("rate_date", sa.Date(), nullable=False),
        sa.Column("rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_key_rates")),
        sa.UniqueConstraint("rate_date", name=op.f("uq_key_rates_rate_date")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("key_rates")
    # ### end Alembic commands ###
