"""add splits

Revision ID: 47f527d22897
Revises: ce70ca1b51d0
Create Date: 2026-06-11 03:49:22.283490

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "47f527d22897"
down_revision: str | Sequence[str] | None = "ce70ca1b51d0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "splits",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("security_id", sa.BigInteger(), nullable=False),
        sa.Column("split_date", sa.Date(), nullable=False),
        sa.Column("before", sa.BigInteger(), nullable=False),
        sa.Column("after", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["security_id"], ["securities.id"], name=op.f("fk_splits_security_id_securities")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_splits")),
        sa.UniqueConstraint(
            "security_id", "split_date", name=op.f("uq_splits_security_id_split_date")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("splits")
    # ### end Alembic commands ###
