"""initial schema

Revision ID: ce70ca1b51d0
Revises:
Create Date: 2026-06-11 03:02:42.645980

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ce70ca1b51d0"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot_subscriptions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "sentiment_spike",
                "volatility_regime",
                "dividend_upcoming",
                "price_level",
                name="alertkind",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "params",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_subscriptions")),
    )
    op.create_table(
        "collector_runs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("success", "partial", "failed", name="collectorrunstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("records_added", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collector_runs")),
    )
    op.create_table(
        "currency_rates",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "currency",
            sa.Enum("RUB", "USD", "EUR", "CNY", name="currency", native_enum=False),
            nullable=False,
        ),
        sa.Column("rate_date", sa.Date(), nullable=False),
        sa.Column("rate", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_currency_rates")),
        sa.UniqueConstraint(
            "currency", "rate_date", name=op.f("uq_currency_rates_currency_rate_date")
        ),
    )
    op.create_table(
        "index_values",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("index_code", sa.String(length=16), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("close", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_index_values")),
        sa.UniqueConstraint(
            "index_code", "trade_date", name=op.f("uq_index_values_index_code_trade_date")
        ),
    )
    op.create_table(
        "news_articles",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_news_articles")),
        sa.UniqueConstraint("url", name=op.f("uq_news_articles_url")),
    )
    op.create_table(
        "securities",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("ticker", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("board", sa.String(length=16), nullable=False),
        sa.Column(
            "aliases",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_securities")),
        sa.UniqueConstraint("ticker", name=op.f("uq_securities_ticker")),
    )
    op.create_table(
        "candles",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("security_id", sa.BigInteger(), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("open", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("high", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("low", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("close", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.Column("value", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column(
            "is_weekend_session", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["security_id"], ["securities.id"], name=op.f("fk_candles_security_id_securities")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candles")),
        sa.UniqueConstraint(
            "security_id", "trade_date", name=op.f("uq_candles_security_id_trade_date")
        ),
    )
    op.create_table(
        "dividends",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("security_id", sa.BigInteger(), nullable=False),
        sa.Column("ex_date", sa.Date(), nullable=False),
        sa.Column("value", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column(
            "currency",
            sa.Enum("RUB", "USD", "EUR", "CNY", name="currency", native_enum=False),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["security_id"], ["securities.id"], name=op.f("fk_dividends_security_id_securities")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dividends")),
        sa.UniqueConstraint(
            "security_id", "ex_date", name=op.f("uq_dividends_security_id_ex_date")
        ),
    )
    op.create_table(
        "news_sentiment",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "label",
            sa.Enum("positive", "neutral", "negative", name="sentimentlabel", native_enum=False),
            nullable=False,
        ),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["news_articles.id"],
            name=op.f("fk_news_sentiment_article_id_news_articles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_news_sentiment")),
        sa.UniqueConstraint("article_id", name=op.f("uq_news_sentiment_article_id")),
    )
    op.create_table(
        "news_tickers",
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("security_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["news_articles.id"],
            name=op.f("fk_news_tickers_article_id_news_articles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.id"],
            name=op.f("fk_news_tickers_security_id_securities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("article_id", "security_id", name=op.f("pk_news_tickers")),
    )
    op.create_table(
        "portfolio_positions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("security_id", sa.BigInteger(), nullable=False),
        sa.Column("quantity", sa.BigInteger(), nullable=False),
        sa.Column("avg_price", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.id"],
            name=op.f("fk_portfolio_positions_security_id_securities"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_positions")),
        sa.UniqueConstraint("security_id", name=op.f("uq_portfolio_positions_security_id")),
    )
    op.create_table(
        "predictions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("security_id", sa.BigInteger(), nullable=False),
        sa.Column("predicted_for", sa.Date(), nullable=False),
        sa.Column("horizon_days", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("volatility", "trend", name="predictionkind", native_enum=False),
            nullable=False,
        ),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["security_id"], ["securities.id"], name=op.f("fk_predictions_security_id_securities")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_predictions")),
        sa.UniqueConstraint(
            "security_id",
            "predicted_for",
            "horizon_days",
            "kind",
            "model_version",
            name="uq_predictions_natural_key",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("predictions")
    op.drop_table("portfolio_positions")
    op.drop_table("news_tickers")
    op.drop_table("news_sentiment")
    op.drop_table("dividends")
    op.drop_table("candles")
    op.drop_table("securities")
    op.drop_table("news_articles")
    op.drop_table("index_values")
    op.drop_table("currency_rates")
    op.drop_table("collector_runs")
    op.drop_table("bot_subscriptions")
    # ### end Alembic commands ###
